import {
  NAV_ITEM_TYPE_TITLE,
  // NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "@/constants/navigation.constant";

const navigationConfig = [
  {
    key: "main",
    path: "",
    title: "Main",
    translateKey: "nav.main.main",
    icon: "main",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "main.dashboard",
        path: "/dashboard",
        title: "Dashboard",
        translateKey: "nav.main.dashboard",
        icon: "dashboard",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "main.stores",
        path: "/stores",
        title: "Stores",
        translateKey: "nav.main.stores",
        icon: "stores",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "main.users",
        path: "/users",
        title: "Users",
        translateKey: "nav.main.users",
        icon: "users",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  // {
  //   key: "pricing",
  //   path: "",
  //   title: "Pricing",
  //   translateKey: "nav.pricing.pricing",
  //   icon: "pricing",
  //   type: NAV_ITEM_TYPE_TITLE,
  //   authority: [],
  //   subMenu: [
  //     {
  //       key: "pricing.tariffs",
  //       path: "/tariffs",
  //       title: "Tariffs",
  //       translateKey: "nav.pricing.tariffs",
  //       icon: "tariffs",
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: [],
  //       subMenu: [],
  //     },
  //     {
  //       key: "pricing.features",
  //       path: "/features",
  //       title: "Features",
  //       translateKey: "nav.pricing.features",
  //       icon: "features",
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: [],
  //       subMenu: [],
  //     },
  //   ],
  // },
  {
    key: "settings",
    path: "",
    title: "Settings",
    translateKey: "nav.settings.settings",
    icon: "settings",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "settings.storeCategories",
        path: "/store-categories",
        title: "Store Categories",
        translateKey: "nav.settings.store_categories",
        icon: "storeCategories",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "settings.countries",
        path: "/countries",
        title: "Countries",
        translateKey: "nav.setings.countries",
        icon: "countries",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "settings.currencies",
        path: "/currencies",
        title: "Currencies",
        translateKey: "nav.settings.currencies",
        icon: "currencies",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
];

export default navigationConfig;
